### ISSUE TITLE
Needs LANG/LC_ALL environment variables

### ISSUE THREAD

**Issue by elvis-epx** [tdsmith/homebrew-ham#11]
```
/Users/epx $ echo $LANG

/Users/epx $ echo $LC_ALL

/Users/epx $ chirpw
Traceback (most recent call last):
  File "/usr/local/bin/chirpw", line 60, in <module>
    lc, encoding = locale.getdefaultlocale()
  File "/usr/local/Cellar/chirp/20180316/libexec/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/chirp/20180316/libexec/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

/Users/epx $ export LANG=en_US.UTF-8
/Users/epx $ export LC_ALL=en_US.UTF-8
/Users/epx $ chirpw
```
  ... (loads) ...

**Comment by tdsmith** [comment]
Hi, thanks for the report. I think your system is misconfigured; the absence of those environment variables does not cause `locale.getdefaultlocale()` to throw an exception on my system.
