### ISSUE TITLE
brew install fails on Mojave

### ISSUE THREAD

**Issue by toddbertels** [tdsmith/homebrew-ham#15]
Traceback (most recent call last):
  File "/private/tmp/chirp--homebrew-virtualenv-20181111-59350-1pcztsn/target/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==16.0.0', 'console_scripts', 'virtualenv')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/private/tmp/chirp--homebrew-virtualenv-20181111-59350-1pcztsn/target/lib/python2.7/site-packages/virtualenv.py", line 22, in <module>
    import zlib
ImportError: No module named zlib

**Comment by yottalogical** [comment]
I can confirm that it still runs just fine in the latest version of Mojave, and that I installed it in the past using Homebrew.

**Comment by masukomi** [comment]
I'm encountering the same zlib problem as @toddbertels but my error message is slightly different (line 33) Furthermore, I definitely have zlib installed 


```
$ brew info chirp
tdsmith/ham/chirp: stable 20181014
Programs amateur radios
http://chirp.danplanet.com/projects/chirp/wiki/Home
Not installed
From: https://github.com/tdsmith/homebrew-ham/blob/master/chirp.rb
==> Dependencies
Required: gtk-mac-integration ✔, libxml2 --with-python ✔, py2cairo ✔, pygtk ✔, python@2 ✔

$ brew install tdsmith/ham/chirp
==> Installing chirp from tdsmith/ham
==> Downloading https://trac.chirp.danplanet.com/chirp_daily/daily-20181014/chirp-daily-20181014.tar.gz
Already downloaded: /Users/masukomi/Library/Caches/Homebrew/downloads/cd200b1aa50435e87c2a48793f4589ada7ca06295f71779b33e8de0d1f222dff--chirp-daily-20181014.tar.gz
==> Downloading https://files.pythonhosted.org/packages/4e/8b/75469c270ac544265f0020aa7c4ea925c5284b23e445cf3aa8b99f662690/virtualenv-16.1.0.tar.gz
Already downloaded: /Users/masukomi/Library/Caches/Homebrew/downloads/bda8bcde19a275fd9c84a7ec957593976e90dfd0e461a87f5698f1d2286c0197--virtualenv-16.1.0.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/chirp--homebrew-virtualenv-20181113-44450-f7w24/target --install-scripts=/private/tmp/chirp--hom
==> python2 -s /private/tmp/chirp--homebrew-virtualenv-20181113-44450-f7w24/target/bin/virtualenv -p python2 /usr/local/Cellar/chirp/20181014/libexec
Last 15 lines from /Users/masukomi/Library/Logs/Homebrew/chirp/02.python2:

Traceback (most recent call last):
  File "/private/tmp/chirp--homebrew-virtualenv-20181113-44450-f7w24/target/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==16.1.0', 'console_scripts', 'virtualenv')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/private/tmp/chirp--homebrew-virtualenv-20181113-44450-f7w24/target/lib/python2.7/site-packages/virtualenv.py", line 33, in <module>
    import zlib
ImportError: No module named zlib


$ brew install zlib
Warning: zlib 1.2.11 is already installed and up-to-date
To reinstall 1.2.11, run `brew reinstall zlib`
```

**Comment by gregghoward** [comment]
I am having a problem too; I have the latest Mojave.

Updating Homebrew...
==> Installing chirp from tdsmith/ham
==> Downloading https://trac.chirp.danplanet.com/chirp_daily/daily-20181014/chirp-daily-20181014.tar.
Already downloaded: /Users/gregghoward/Library/Caches/Homebrew/downloads/cd200b1aa50435e87c2a48793f4589ada7ca06295f71779b33e8de0d1f222dff--chirp-daily-20181014.tar.gz
==> Downloading https://files.pythonhosted.org/packages/4e/8b/75469c270ac544265f0020aa7c4ea925c5284b2
Already downloaded: /Users/gregghoward/Library/Caches/Homebrew/downloads/bda8bcde19a275fd9c84a7ec957593976e90dfd0e461a87f5698f1d2286c0197--virtualenv-16.1.0.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/chirp--homebrew-virtu
Last 15 lines from /Users/gregghoward/Library/Logs/Homebrew/chirp/01.python2:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/chirp--homebrew-virtualenv-20181220-45885-83mq6q/target
--install-scripts=/private/tmp/chirp--homebrew-virtualenv-20181220-45885-83mq6q/target/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

**Comment by frankhuster** [comment]
Also getting an error installing (on Mojave 10.14.2)
```
$ brew install tdsmith/ham/chirp
==> Installing chirp from tdsmith/ham
==> Downloading https://trac.chirp.danplanet.com/chirp_daily/daily-20181014/chirp-daily-20181014.tar.gz
Already downloaded: /Users/frankie/Library/Caches/Homebrew/downloads/cd200b1aa50435e87c2a48793f4589ada7ca06295f71779b33e8de0d1f222dff--chirp-daily-20181014.tar.gz
==> Downloading https://github.com/pypa/virtualenv/archive/16.2.0.tar.gz
Already downloaded: /Users/frankie/Library/Caches/Homebrew/downloads/bfb26e5e9fbf90082f14312f9f0af39c489fc665de9adcc2c003f3e4c533bfd6--virtualenv-16.2.0.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/chirp--homebrew-virtualenv-20190109-89170-e1vrfl/target --install-scripts=/private/tmp/chirp--homebrew-virtualenv
==> python2 -s /private/tmp/chirp--homebrew-virtualenv-20190109-89170-e1vrfl/target/bin/virtualenv -p python2 /usr/local/Cellar/chirp/20181014/libexec
==> Downloading https://files.pythonhosted.org/packages/1f/3b/ee6f354bcb1e28a7cd735be98f39ecf80554948284b41e9f7965951befa6/pyserial-3.2.1.tar.gz
Already downloaded: /Users/frankie/Library/Caches/Homebrew/downloads/02f61bdae6cc8872d79c013487edd1005203f8d4a4ffc21ac75d122ed75b4f5f--pyserial-3.2.1.tar.gz
==> /usr/local/Cellar/chirp/20181014/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/chirp--pyserial-20190109-89170-oscjj3/pyserial-3.2.1
==> /usr/local/Cellar/chirp/20181014/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/chirp-20190109-89170-1kecquw/chirp-daily-20181014
Last 15 lines from /Users/frankie/Library/Logs/Homebrew/chirp/04.pip:
  File "/usr/local/Cellar/chirp/20181014/libexec/lib/python2.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/Cellar/chirp/20181014/libexec/lib/python2.7/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/Cellar/chirp/20181014/libexec/lib/python2.7/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/Cellar/chirp/20181014/libexec/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/Cellar/chirp/20181014/libexec/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 126, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/local/Cellar/chirp/20181014/libexec/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 473, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/Cellar/chirp/20181014/libexec/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-E4lw31/

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tdsmith/homebrew-ham/issues

$
```
