### ISSUE TITLE
brew install fails

### ISSUE THREAD

**Issue by krisrice** [tdsmith/homebrew-ham#3]
The install via brew fails with the following on Sierra 10.12.6 

==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/chirp--homebrew-virtualenv-20170828-67100-xs4adb/target --sin
Last 15 lines from /Users/klrice/Library/Logs/Homebrew/chirp/01.python:
--no-user-cfg
install
--prefix=/tmp/chirp--homebrew-virtualenv-20170828-67100-xs4adb/target
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, map
  File "/usr/local/lib/python2.7/site-packages/setuptools/setuptools/__init__.py", line 160, in <module>
    monkey.patch_all()
  File "/usr/local/lib/python2.7/site-packages/setuptools/setuptools/monkey.py", line 48, in patch_all
    distutils.core.Command = setuptools.Command
AttributeError: 'module' object has no attribute 'Command'

**Comment by tdsmith** [comment]
Hmm! I'll try this when I get home tonight to make sure it still works for me. Can you share the output of `brew doctor`?

**Comment by tdsmith** [comment]
I couldn't reproduce this, sorry.
